

services:
  db-mysql:
    image: mysql:8.0
    container_name: db-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
    depends_on:
      config-server:
        condition: service_healthy
      eureka:
        condition: service_healthy


  blog:
    build: ./blog
    container_name: blog
    ports:
      - "8082:8082"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,swagger-ui
    depends_on:
      db-mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka:
        condition: service_healthy

  carrito:
    build: ./carrito
    container_name: carrito
    ports:
      - "8083:8083"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,swagger-ui
    depends_on:
      db-mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka:
        condition: service_healthy

  reserva:
    build: ./reserva
    container_name: reserva
    ports:
      - "8084:8084"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,swagger-ui
    depends_on:
      db-mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka:
        condition: service_healthy

  notificaciones:
    build: ./notificaciones
    container_name: notificaciones
    ports:
      - "8085:8085"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
    depends_on:
      config-server:
        condition: service_healthy
      eureka:
        condition: service_healthy

  comentario:
    build: ./comentarios
    container_name: comentario
    ports:
      - "8086:8086"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,swagger-ui
    depends_on:
      db-mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka:
        condition: service_healthy

  libro:
    build: ./libro
    container_name: libro
    ports:
      - "8087:8087"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,swagger-ui
    depends_on:
      db-mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka:
        condition: service_healthy

  prestamos:
    build: ./prestamos
    container_name: prestamos
    ports:
      - "8088:8088"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,swagger-ui
    depends_on:
      db-mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka:
        condition: service_healthy

  usuarios:
    build: ./usuarios
    container_name: usuarios
    ports:
      - "8089:8089"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,swagger-ui
    depends_on:
      db-mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka:
        condition: service_healthy

  inventario:
    build: ./inventario
    container_name: inventario
    ports:
      - "8091:8091"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,swagger-ui
    depends_on:
      db-mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka:
        condition: service_healthy

  talleres:
    build: ./talleres
    container_name: talleres
    ports:
      - "8092:8092"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,swagger-ui
    depends_on:
      db-mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka:
        condition: service_healthy


volumes:
  mysql_data: